export const EX_PAGE_CONFIGURING_EX = 'EX_PAGE_CONFIGURING_EX';
export const EX_PAGE_TRAINING = 'EX_PAGE_TRAINING';
export const EX_PAGE_SEEING_RESULTS = 'EX_PAGE_SEEING_RESULTS';
export const EX_PAGE_LOADING_EXERCISE = 'EX_PAGE_LOADING_EXERCISE';